### PR TITLE
fix deprecated brews.github config of goreleaser

### PR DESCRIPTION
**Pull request by haya14busa**
https://goreleaser.com/deprecations/#brewsgithub

### CODE REVIEW

**Comment by haya14busa** [comment]
Looks ok. https://github.com/reviewdog/reviewdog/pull/981/checks?check_run_id=2920986700

**Comment by haya14busa** [comment]
@shogo82148 Can you delete the tag  v0.12.0 first, add bump:minor label, and review&merge this p-r?
This pr fixes the release failure in #979

**Review by shogo82148 — APPROVED** [review]
LGTM!

**Comment by haya14busa** [comment]
Thank you, shogo-san!

**Pull request merged**
