### PR TITLE
Return false on HasReadOnlyPermissionGitHubToken by environment variable

### PR DESCRIPTION
**Pull request by furushchev**
This PR adds a way to return `false` from the `HasReadOnlyPermissionGitHubToken` 
 when the environment variable `REVIEWDOG_GITHUB_ACTIONS_TOKEN_HAS_WRITE_PERMISSION` is defined.

Since there is no way to check the available scope of the token provided by Github for now, I believe this is the simplest workaround for the issue such as https://github.com/reviewdog/reviewdog/issues/1210.

- [x] Updated Unreleased section in [CHANGELOG](https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md) or it's not notable changes.

### CODE REVIEW

**Comment by furushchev** [comment]
Kindly ping to a maintainer @haya14busa

**Comment by OnkarRuikar** [comment]
+1 Bumping this.
There is a valid [way to give the GITHUB_TOKEN write permissions in triggered `workflow_run` workflows](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/). This works well with workflows triggered by PRs from forked repos.\
We are [trying to implement reviewdog](https://github.com/yin1999/translated-content/pull/19#issuecomment-1661533931) for [`mdn/content`](https://github.com/mdn/content) repo and we are waiting for this(such) solution to allow tokens with write permissions.

**Comment by furushchev** [comment]
@haya14busa @shogo82148 Kindly ping to maintainers.

I resolved the conflict.

**Review by benjGam — APPROVED** [review]

**Comment by furushchev** [comment]
@benjGam Thank you for your review! I resolved the conflict by merging `origin/master`.
Please review this PR again and merge it if it looks good!

**Comment by haya14busa** [comment]
Closing it in favor of #1521.

**Pull request closed without merging**
