### PR TITLE
Add Bitbucket Server support for 'bitbucket-code-report' reporter

### PR DESCRIPTION
**Pull request by reva2**
This PR add support for Bitbucket Server using Code Insights API available starting from version 5.15:

- [https://confluence.atlassian.com/bitbucketserver/code-insights-966660485.html](https://confluence.atlassian.com/bitbucketserver/code-insights-966660485.html)
- [https://docs.atlassian.com/bitbucket-server/rest/5.15.0/bitbucket-code-insights-rest.html#idm288218258672](https://docs.atlassian.com/bitbucket-server/rest/5.15.0/bitbucket-code-insights-rest.html#idm288218258672)

### CODE REVIEW

**Comment by reva2** [comment]
Hi @shogo82148 
Sorry for the importunity. Can you review this PR and let me know if anything need to be changed so it can be merged to main branch?

**Comment by reva2** [comment]
I assume I fixed all issues reported by `golangci-lint`. Please approve workflow run to be sure.

**Review by shogo82148 — APPROVED** [review]
LGTM

**Comment by reva2** [comment]
Hi @shogo82148 
Thanks for review. Can you publish new version with Bitbucket Server support so we can integrate it in our CI processes?

**Comment by shogo82148** [comment]
I created a release branch https://github.com/reviewdog/reviewdog/pull/1003
However some reviews are required to merge it.

@reva2 should be able to review it, but the invite workflow is disable... https://github.com/reviewdog/inviter/actions/workflows/invite.yml
I have no permission to enable it. 😿

**Comment by review-dog** [comment]
Hi, @reva2! We merged your PR to reviewdog! 🐶
Thank you for your contribution! ✨

**We just invited you to join the @reviewdog organization on GitHub.**
Accept the invite by visiting https://github.com/orgs/reviewdog/invitation.
By joining the team, you'll be a part of reviewdog community and can help the maintainance of reviewdog.

Thanks again!

**Pull request merged**
