### PR TITLE
Use Gitlab suggestions in merge request comments

### PR DESCRIPTION
**Pull request by tiena2cva**
Follow #678, this pull request allow use Gitlab suggestions in merge request discussion

Most of code in this PR come from #842 but the author @caseycs is inactive for a long time, I create a new one.

Please take a look @haya14busa

### CODE REVIEW

**Comment by tiena2cva** [comment]
@haya14busa could you please take a look?

**Review by shogo82148 — APPROVED** [review]
LGTM

**Comment by review-dog** [comment]
Hi, @tiena2cva! We merged your PR to reviewdog! 🐶
Thank you for your contribution! ✨

**We just invited you to join the @reviewdog organization on GitHub.**
Accept the invite by visiting https://github.com/orgs/reviewdog/invitation.
By joining the team, you'll be a part of reviewdog community and can help the maintainance of reviewdog.

Thanks again!

**Comment by oxinabox** [comment]
Readme right now says suggestions are not supported in GitLab, is that out of date?

**Comment by zzvvmm** [comment]
> Readme right now says suggestions are not supported in GitLab, is that out of date?

I found `gitlab-mr-discussion` worked but there are some trouble you need to deal with. .e.g. this issue
https://github.com/reviewdog/reviewdog/issues/1282#issuecomment-1354149286
Maybe you can give a try with your lint to see the whether if can run with GitLab suggestion

**Pull request merged**
