### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ques0942**
go-github was bumped up from [v25 to v26](https://github.com/google/go-github/commit/3c0a06186fba843ee65689877b7def4685d91d0a).
This PR follow it.

All unit tests passed.
If I have any other tests, Please tell me that :P

refs: #223

### CODE REVIEW

**Comment by shogo82148** [comment]
https://travis-ci.org/reviewdog/reviewdog/jobs/544561733

installing honnef.co/go/tools/cmd/gosimple is failing. :(

```
$ go get honnef.co/go/tools/cmd/gosimple
go: finding honnef.co/go/tools/cmd/gosimple latest
go: finding honnef.co/go/tools latest
go: downloading honnef.co/go/tools v0.0.0-20190607181801-497c8f037f5a
go: extracting honnef.co/go/tools v0.0.0-20190607181801-497c8f037f5a
go get honnef.co/go/tools/cmd/gosimple: module honnef.co/go/tools@latest (v0.0.0-20190607181801-497c8f037f5a) found, but does not contain package honnef.co/go/tools/cmd/gosimple
The command "go get honnef.co/go/tools/cmd/gosimple" failed and exited with 1 during .
```

@haya14busa Can we disable honnef.co/go/tools temporarily? It is noisy and blocks merging.

**Comment by shogo82148** [comment]
I got it.
honnef.co/go/tools should include the major version in its import path. e.g. `honnef.co/go/tools/v2019/cmd/gosimple`, but it doesn't.

my workaround is here https://github.com/reviewdog/reviewdog/pull/224

**Comment by ques0942** [comment]
Sorry. I had have to notice it and now I can't fix it.
I will try it later. m(_ _)m

**Comment by ques0942** [comment]
Which should I do whether merging `shogo82148:workaround-for-honnef.co-go-tools` branch to this or waiting for #224 ?

**Comment by haya14busa** [comment]
Can you rebase/merge master and fix travis build?

**Comment by haya14busa** [comment]
Probably, we can remove v{n} path from the code now, but not required for this p-r.

**Comment by ques0942** [comment]
I merged the master branch to this PR, but Travis-CI's build job failed.
I'm investigating the cause(re-run might fix it...)

**Comment by ques0942** [comment]
I executed install commands which are on Travis config, but these succeed.
I think it is a temporary error, please re-start Travis-CI build job. I have no permission so can't do that.

**Comment by haya14busa** [comment]
THanks!

**Pull request merged**
