### PR TITLE
Add a fallback to git diff command to get diff of a GitHub pull request on doghouse

### PR DESCRIPTION
**Pull request by massongit**
- [x] Updated Unreleased section in [CHANGELOG](https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md) or it's not notable changes.

Fix https://github.com/reviewdog/reviewdog/issues/1696#issuecomment-2074711580

Similar to https://github.com/reviewdog/reviewdog/pull/1697 and https://github.com/reviewdog/reviewdog/pull/1714, I add a fallback to `git diff` command to get diff of a GitHub pull request on doghouse.

https://github.com/reviewdog/reviewdog/blob/8e405abb08572c6336a1bd6800c1bf68953c633f/cmd/reviewdog/main.go#L302-L307
This will enable fallback even if the reporter is `github-check`, `github-pr-check` or `github-pr-annotations`.

Note that this only runs if `git` command is installed.

### CODE REVIEW

**Comment by massongit** [comment]
@haya14busa Please review it.

**Comment by dprotaso** [comment]
Hey just following up - we've been hitting this issue again.

**Comment by massongit** [comment]
@haya14busa @shogo82148 Please review it.

**Review by haya14busa — APPROVED** [review]
I'm sorry for the very late review.

I added some commits to this PR and LGTM.

**Pull request merged**
