### PR TITLE
docs: List GitLab Suggestion as Implemented

### PR DESCRIPTION
**Pull request by JamesMConroy**
The GitLab merge request discussion reporter definitely supports the suggestion feature.

Looks like it was added in https://github.com/reviewdog/reviewdog/pull/1012

No need to update the change log since this is just a docs change.

### CODE REVIEW

**Review by shogo82148 — APPROVED** [review]

**Comment by lafriks** [comment]
Probably needs to merge changes from master so that status checks are run

**Comment by JamesMConroy** [comment]
> Probably needs to merge changes from master so that status checks are run

Done, but I don't know if that's the hold up. On my end it says that the workflows need approval to run.

image

**Comment by JamesMConroy** [comment]
@shogo82148 @kepten do either of you know who needs to approve the workflows so that they will run?

**Comment by review-dog** [comment]
Hi, @JamesMConroy! We merged your PR to reviewdog! 🐶
Thank you for your contribution! ✨

**We just invited you to join the @reviewdog organization on GitHub.**
Accept the invite by visiting https://github.com/orgs/reviewdog/invitation.
By joining the team, you'll be a part of reviewdog community and can help the maintenance of reviewdog.

Thanks again!

**Pull request merged**
