### PR TITLE
Check for GITHUB_ACTIONS instead of GITHUB_ACTION 

### LINKED ISSUE #708: Determining if reviewdog is working in GitHub Actions or not is broken because of runner's regression
reviewdog checks for `GITHUB_ACTION` context variable in order to determine it's running in GitHub Actions or not. 

https://github.com/reviewdog/reviewdog/blob/31a1260dd0b95c3adb4629d8ef32e3207081d914/cienv/github_actions.go#L99-L103

However `GITHUB_ACTION` context variable has become empty in recent updates, so currently this check always fails.

ref. https://github.com/actions/runner/issues/635

As a result, running reviewdog in GitHub Actions always fails with this error: `reviewdog: cannot get repo owner from environment variable. Set CI_REPO_OWNER?`.

https://github.com/reviewdog/reviewdog/blob/c9d205fb4143e6c35c77f8885a27e71d666f90fb/cienv/cienv.go#L53-L55

I think this is a regression of GitHub Actions' runner, but I also think it's reasonable to mitigate this problem by checking another context variables such as `GITHUB_ACTIONS` like codecov/codecov-bash does:

https://github.com/codecov/codecov-bash/pull/341

### PR DESCRIPTION
**Pull request by polamjag**
fixes #708 

- [x] Updated Unreleased section in [CHANGELOG](https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md) or it's not notable changes.

### CODE REVIEW

**Comment by polamjag** [comment]
CI fails due to the problem I would like to fix 🤔

**Comment by shmokmt** [comment]
I'm facing the same problem.

**Comment by johnboyes** [comment]
Me three.

**Comment by Songmu** [comment]
Oops, I made the same change, but you were faster.
But it seems better to fix the test. Please refer to my fix. #710 

@polamjag

**Comment by Songmu** [comment]
It seems a temporary bug in GITHUB_ACTIONS itself, but looking at the documentation, it seems that making sure the GITHUB_ACTIONS variable is set to true is a more correct way to determine if it's working on GitHub Actions.

- bug issue: https://github.com/actions/runner/issues/635
- document: https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables

So I think this change is acceptable. How do you think? @haya14busa

**Comment by review-dog** [comment]
Hi, @polamjag! We merged your PR to reviewdog! 🐶
Thank you for your contribution! ✨

**We just invited you to join the @reviewdog organization on GitHub.**
Accept the invite by visiting https://github.com/orgs/reviewdog/invitation.
By joining the team, you'll be a part of reviewdog community and can help the maintainance of reviewdog.

Thanks again!

**Comment by JGJP** [comment]
Can we expect this to be released soon?

**Comment by polamjag** [comment]
@haya14busa @Songmu Thanks!! 👍👍👍

**Comment by haya14busa** [comment]
Release v0.10.2 (#711) and update most public reviewdog actions maintained under reviewdog org as well.

**Comment by johnboyes** [comment]
> Released v0.10.2 (#711) and update most public reviewdog actions maintained under reviewdog org as well.

Thanks to everyone involved for the quick turnaround on this.

Looks like https://github.com/reviewdog/action-yamllint is one of the actions that has not had the fix applied yet, FYI.

**Comment by shogo82148** [comment]
It looks that action-yamllint doesn't have Automated Dependencies Update workflow.
I will introduce it.
https://github.com/reviewdog/action-yamllint/issues/5

**Comment by johnboyes** [comment]
That's great, @shogo82148.  
I have created a blunt temporary fix in https://github.com/johnboyes/action-yamllint/commit/dd95d1f868d08a2590f48ceae837b0e270858b78  (I've tested it and it works) - should I create a PR for it to be applied in the short-term?

**Pull request merged**
