### PR TITLE
bump v0.12.0

### PR DESCRIPTION
**Pull request by shogo82148**
- [x] Updated Unreleased section in [CHANGELOG](https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md) or it's not notable changes.

### CODE REVIEW

**Review by haya14busa — APPROVED** [review]
Thanks!

**Comment by haya14busa** [comment]
goreleaser failed... 😢  https://github.com/reviewdog/reviewdog/runs/2920840279?check_suite_focus=true

**Comment by haya14busa** [comment]
@shogo82148 

btw, can you delete the remote tag? Do you have permission?
```sh
git push origin :refs/tags/v0.12.0
```

**Comment by shogo82148** [comment]
@haya14busa 

Yes, I can edit and delete tags.

image

Do I ?

**Comment by haya14busa** [comment]
oh, I didn't know we can do this from GitHub UI.

Yes, can you try deleting the tag once to retry release?

**Pull request merged**
